# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"\x16\n\x08SensorId\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\x07Reading\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\n\n\x02ts\x18\x04 \x01(\x01\"-\n\nSetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x32\x93\x01\n\rSensorService\x12(\n\x03Get\x12\x10.sensor.SensorId\x1a\x0f.sensor.Reading\x12*\n\x03Set\x12\x12.sensor.SetRequest\x1a\x0f.sensor.Reading\x12,\n\x05Watch\x12\x10.sensor.SensorId\x1a\x0f.sensor.Reading0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORID']._serialized_start=24
  _globals['_SENSORID']._serialized_end=46
  _globals['_READING']._serialized_start=48
  _globals['_READING']._serialized_end=116
  _globals['_SETREQUEST']._serialized_start=118
  _globals['_SETREQUEST']._serialized_end=163
  _globals['_SENSORSERVICE']._serialized_start=166
  _globals['_SENSORSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
