# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sensor_pb2 as sensor__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/sensor.SensorService/Get',
                request_serializer=sensor__pb2.SensorId.SerializeToString,
                response_deserializer=sensor__pb2.Reading.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/sensor.SensorService/Set',
                request_serializer=sensor__pb2.SetRequest.SerializeToString,
                response_deserializer=sensor__pb2.Reading.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/sensor.SensorService/Watch',
                request_serializer=sensor__pb2.SensorId.SerializeToString,
                response_deserializer=sensor__pb2.Reading.FromString,
                _registered_method=True)


class SensorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """한 번 묻고 한 번 받는다. REST의 GET에 해당한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """값을 올린다. REST의 PUT에 해당한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """서버가 값을 계속 밀어 준다. REST에는 이런 것이 없다.
        WebSocket으로 직접 짜야 했던 일을 여기서는 한 줄로 선언한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=sensor__pb2.SensorId.FromString,
                    response_serializer=sensor__pb2.Reading.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=sensor__pb2.SetRequest.FromString,
                    response_serializer=sensor__pb2.Reading.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=sensor__pb2.SensorId.FromString,
                    response_serializer=sensor__pb2.Reading.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensor.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensor.SensorService/Get',
            sensor__pb2.SensorId.SerializeToString,
            sensor__pb2.Reading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensor.SensorService/Set',
            sensor__pb2.SetRequest.SerializeToString,
            sensor__pb2.Reading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensor.SensorService/Watch',
            sensor__pb2.SensorId.SerializeToString,
            sensor__pb2.Reading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
